# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
#highlighter: pygments
highlighter: rouge
markdown: kramdown
#disqus: dbyll
google_analytics: UA-68435855-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Carlos Albornoz

description: rocking since MCMLXXXII
author:
  name: Carlos Albornoz
  email: carlos@albornoz.rocks
  github: dubcl
  twitter: dubcl
  pinterest: dubcl
  linkedin: carlosalbornoz
  bio: rocking since MCMLXXXII
  email_md5: c12e48089277b04398ae012fdc4829cb

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

